/**
 * Plugins Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration:
 * 1. Create a new directory in plugins/ (e.g., plugins/my-integration/)
 * 2. Add your plugin files (index.tsx, steps/, codegen/, etc.)
 * 3. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * To remove an integration:
 * 1. Delete the plugin directory
 * 2. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * Discovered plugins: code, discord, math, offramp, persona, protocol, request-finance, sablier, safe, sendgrid, slack, superchain, superfluid, telegram, web3, webhook, xmtp
 */

import "./code";
import "./discord";
import "./math";
import "./offramp";
import "./persona";
import "./protocol";
import "./request-finance";
import "./sablier";
import "./safe";
import "./sendgrid";
import "./slack";
import "./superchain";
import "./superfluid";
import "./telegram";
import "./web3";
import "./webhook";
import "./xmtp";
