import type { IntegrationPlugin } from "@/plugins/registry";
import { registerIntegration } from "@/plugins/registry-core";
import { SuperfluidIcon } from "./icon";

const superfluidPlugin: IntegrationPlugin = {
  type: "superfluid",
  label: "Superfluid",
  description: "Read and manage Superfluid token streams",
  icon: SuperfluidIcon,
  requiresCredentials: false,
  formFields: [],
  actions: [
    {
      slug: "get-incoming-streams",
      label: "Get Incoming Streams",
      description:
        "List active incoming Superfluid streams for a wallet and return flow rates",
      category: "Superfluid",
      stepFunction: "getIncomingStreamsStep",
      stepImportPath: "get-incoming-streams",
      configFields: [
        {
          key: "network",
          label: "Network",
          type: "chain-select",
          chainTypeFilter: "evm",
          placeholder: "Select network",
          required: true,
        },
        {
          key: "walletAddress",
          label: "Wallet Address",
          type: "template-input",
          placeholder: "0x... or {{NodeName.address}}",
          required: true,
          isAddressField: true,
        },
        {
          key: "tokenAddress",
          label: "Token Address (Optional)",
          type: "template-input",
          placeholder: "0x... Super Token address",
          required: false,
          isAddressField: true,
        },
        {
          key: "limit",
          label: "Max Streams",
          type: "number",
          min: 1,
          max: 200,
          defaultValue: "50",
          required: false,
        },
      ],
      outputFields: [
        { field: "success", description: "Whether the read succeeded" },
        { field: "streams", description: "Incoming stream list" },
        { field: "totalFlowRate", description: "Sum of active flow rates" },
        { field: "count", description: "Number of active incoming streams" },
        { field: "error", description: "Error message if failed" },
      ],
    },
    {
      slug: "get-real-time-balance",
      label: "Get Real-Time Balance",
      description:
        "Read realtime balance and flow summary for a Super Token holder",
      category: "Superfluid",
      stepFunction: "getRealTimeBalanceStep",
      stepImportPath: "get-real-time-balance",
      configFields: [
        {
          key: "network",
          label: "Network",
          type: "chain-select",
          chainTypeFilter: "evm",
          placeholder: "Select network",
          required: true,
        },
        {
          key: "walletAddress",
          label: "Wallet Address",
          type: "template-input",
          placeholder: "0x... or {{NodeName.address}}",
          required: true,
          isAddressField: true,
        },
        {
          key: "tokenAddress",
          label: "Super Token Address",
          type: "template-input",
          placeholder: "0x... or {{NodeName.token}}",
          required: true,
          isAddressField: true,
        },
      ],
      outputFields: [
        { field: "success", description: "Whether the read succeeded" },
        {
          field: "availableBalance",
          description: "Realtime available balance (smallest unit)",
        },
        { field: "deposit", description: "Current stream deposit amount" },
        { field: "owedDeposit", description: "Outstanding owed deposit" },
        { field: "timestamp", description: "Chain timestamp from balance call" },
        { field: "totalInflowRate", description: "Current total inflow rate" },
        { field: "totalOutflowRate", description: "Current total outflow rate" },
        { field: "totalNetFlowRate", description: "Current net flow rate" },
        { field: "error", description: "Error message if failed" },
      ],
    },
    {
      slug: "create-outgoing-stream",
      label: "Create Outgoing Stream",
      description:
        "Create or update a stream to a recipient by setting a positive flow rate",
      category: "Superfluid",
      stepFunction: "createOutgoingStreamStep",
      stepImportPath: "create-outgoing-stream",
      requiresCredentials: true,
      credentialIntegrationType: "web3",
      configFields: [
        {
          key: "network",
          label: "Network",
          type: "chain-select",
          chainTypeFilter: "evm",
          showPrivateVariants: true,
          placeholder: "Select network",
          required: true,
        },
        {
          key: "tokenAddress",
          label: "Super Token Address",
          type: "template-input",
          placeholder: "0x... or {{NodeName.token}}",
          required: true,
          isAddressField: true,
        },
        {
          key: "recipientAddress",
          label: "Recipient Address",
          type: "template-input",
          placeholder: "0x... or {{NodeName.address}}",
          required: true,
          isAddressField: true,
        },
        {
          key: "flowRate",
          label: "Flow Rate (wei/sec)",
          type: "template-input",
          placeholder: "3858024691358",
          required: true,
        },
        {
          key: "forwarderAddress",
          label: "CFA Forwarder Address (Optional)",
          type: "template-input",
          placeholder: "0xcfA132E353cB4E398080B9700609bb008eceB125",
          required: false,
          isAddressField: true,
        },
      ],
      outputFields: [
        { field: "success", description: "Whether stream creation succeeded" },
        { field: "transactionHash", description: "On-chain transaction hash" },
        { field: "transactionLink", description: "Explorer transaction link" },
        { field: "gasUsed", description: "Gas used in wei" },
        { field: "error", description: "Error message if failed" },
      ],
    },
    {
      slug: "modify-stream-destination",
      label: "Modify Stream Destination",
      description:
        "Close an active stream and recreate it with a new recipient address",
      category: "Superfluid",
      stepFunction: "modifyStreamDestinationStep",
      stepImportPath: "modify-stream-destination",
      requiresCredentials: true,
      credentialIntegrationType: "web3",
      configFields: [
        {
          key: "network",
          label: "Network",
          type: "chain-select",
          chainTypeFilter: "evm",
          showPrivateVariants: true,
          placeholder: "Select network",
          required: true,
        },
        {
          key: "tokenAddress",
          label: "Super Token Address",
          type: "template-input",
          placeholder: "0x... or {{NodeName.token}}",
          required: true,
          isAddressField: true,
        },
        {
          key: "currentRecipientAddress",
          label: "Current Recipient Address",
          type: "template-input",
          placeholder: "0x... existing recipient",
          required: true,
          isAddressField: true,
        },
        {
          key: "newRecipientAddress",
          label: "New Recipient Address",
          type: "template-input",
          placeholder: "0x... new recipient",
          required: true,
          isAddressField: true,
        },
        {
          key: "newFlowRate",
          label: "New Flow Rate (wei/sec)",
          type: "template-input",
          placeholder: "3858024691358",
          required: true,
        },
        {
          key: "forwarderAddress",
          label: "CFA Forwarder Address (Optional)",
          type: "template-input",
          placeholder: "0xcfA132E353cB4E398080B9700609bb008eceB125",
          required: false,
          isAddressField: true,
        },
      ],
      outputFields: [
        { field: "success", description: "Whether modification succeeded" },
        {
          field: "closedTransactionHash",
          description: "Transaction hash that closed the old stream",
        },
        {
          field: "createdTransactionHash",
          description: "Transaction hash that created the new stream",
        },
        { field: "error", description: "Error message if failed" },
      ],
    },
    {
      slug: "close-stream",
      label: "Close Stream",
      description: "Set a stream flow rate to zero to terminate it",
      category: "Superfluid",
      stepFunction: "closeStreamStep",
      stepImportPath: "close-stream",
      requiresCredentials: true,
      credentialIntegrationType: "web3",
      configFields: [
        {
          key: "network",
          label: "Network",
          type: "chain-select",
          chainTypeFilter: "evm",
          showPrivateVariants: true,
          placeholder: "Select network",
          required: true,
        },
        {
          key: "tokenAddress",
          label: "Super Token Address",
          type: "template-input",
          placeholder: "0x... or {{NodeName.token}}",
          required: true,
          isAddressField: true,
        },
        {
          key: "recipientAddress",
          label: "Recipient Address",
          type: "template-input",
          placeholder: "0x... active recipient",
          required: true,
          isAddressField: true,
        },
        {
          key: "forwarderAddress",
          label: "CFA Forwarder Address (Optional)",
          type: "template-input",
          placeholder: "0xcfA132E353cB4E398080B9700609bb008eceB125",
          required: false,
          isAddressField: true,
        },
      ],
      outputFields: [
        { field: "success", description: "Whether close succeeded" },
        { field: "transactionHash", description: "On-chain transaction hash" },
        { field: "transactionLink", description: "Explorer transaction link" },
        { field: "error", description: "Error message if failed" },
      ],
    },
    {
      slug: "get-stream-events",
      label: "Get Stream Events",
      description:
        "Poll recent stream update events to drive event-triggered workflows",
      category: "Superfluid",
      stepFunction: "getStreamEventsStep",
      stepImportPath: "get-stream-events",
      configFields: [
        {
          key: "network",
          label: "Network",
          type: "chain-select",
          chainTypeFilter: "evm",
          placeholder: "Select network",
          required: true,
        },
        {
          key: "walletAddress",
          label: "Filter Wallet Address (Optional)",
          type: "template-input",
          placeholder: "0x... sender or receiver",
          required: false,
          isAddressField: true,
        },
        {
          key: "fromTimestamp",
          label: "From Timestamp (Unix)",
          type: "template-input",
          placeholder: "1714579200",
          required: false,
        },
        {
          key: "toTimestamp",
          label: "To Timestamp (Unix)",
          type: "template-input",
          placeholder: "1714586400",
          required: false,
        },
        {
          key: "limit",
          label: "Max Events",
          type: "number",
          min: 1,
          max: 500,
          defaultValue: "100",
          required: false,
        },
      ],
      outputFields: [
        { field: "success", description: "Whether polling succeeded" },
        { field: "events", description: "Stream update event list" },
        { field: "count", description: "Number of events returned" },
        { field: "error", description: "Error message if failed" },
      ],
    },
  ],
};

registerIntegration(superfluidPlugin);

export default superfluidPlugin;
